[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_CIRCLES_INDEXER_URL = "https://rpc.aboutcircles.com"

[context.deploy-preview.environment]
  VITE_CIRCLES_INDEXER_URL = "https://rpc.circlesubi.network"

[context.branch-deploy.environment]
  VITE_CIRCLES_INDEXER_URL = "https://rpc.circlesubi.network"
